services:
  frigate-alerts:
    container_name: frigate-alerts
    build: .
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      - ./config:/app/config
    networks:
      - default
      - frigate-net

networks:
  frigate-net:
    external: true
    name: frigate-notify-doubletake_frigate-net
